-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 14:23:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankdb` DEFAULT CHARACTER SET utf8 ;
USE `bankdb` ;

-- -----------------------------------------------------
-- Table `bankdb`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`compte` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NULL,
  `solde` DOUBLE NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`operation` (
  `id_operation` INT NOT NULL AUTO_INCREMENT,
  `montant` DOUBLE NULL,
  `label` VARCHAR(45) NULL,
  `date` DATE NULL,
  `num_compte` INT NOT NULL,
  PRIMARY KEY (`id_operation`),
  INDEX `fk_operation_compte_idx` (`num_compte` ASC) VISIBLE,
  CONSTRAINT `fk_operation_compte`
    FOREIGN KEY (`num_compte`)
    REFERENCES `bankdb`.`compte` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`adresse_pour_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`adresse_pour_client` (
  `rue` VARCHAR(45) NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  CONSTRAINT `fk_adresse_pour_client_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `bankdb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`client_compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankdb`.`client_compte` (
  `id_client` INT NOT NULL,
  `compte_numero` INT NOT NULL,
  PRIMARY KEY (`id_client`, `compte_numero`),
  INDEX `fk_client_has_compte_compte1_idx` (`compte_numero` ASC) VISIBLE,
  INDEX `fk_client_has_compte_client1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_compte_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `bankdb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_compte_compte1`
    FOREIGN KEY (`compte_numero`)
    REFERENCES `bankdb`.`compte` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
