-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 16:46:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventesdb` DEFAULT CHARACTER SET utf8 ;
USE `ventesdb` ;

-- -----------------------------------------------------
-- Table `ventesdb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`produit` (
  `id_produit` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prix_ht` FLOAT NOT NULL,
  `caracteristiques` VARCHAR(250) NULL,
  `url_image` VARCHAR(128) NULL,
  PRIMARY KEY (`id_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventesdb`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`adresse` (
  `id_adresse` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NULL,
  `codePostal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`id_adresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventesdb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `id_adresse` INT NOT NULL,
  `telephone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_client_adresse1_idx` (`id_adresse` ASC) VISIBLE,
  UNIQUE INDEX `id_adresse_UNIQUE` (`id_adresse` ASC) VISIBLE,
  UNIQUE INDEX `clientcol_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`id_adresse`)
    REFERENCES `ventesdb`.`adresse` (`id_adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventesdb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`commande` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATETIME NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_commande_client_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_commande_client`
    FOREIGN KEY (`id_client`)
    REFERENCES `ventesdb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventesdb`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`ligne_commande` (
  `commande_numero` INT NOT NULL,
  `id_produit` INT NOT NULL,
  `quantite` INT NULL DEFAULT 1,
  PRIMARY KEY (`commande_numero`, `id_produit`),
  INDEX `fk_commande_has_produit_produit1_idx` (`id_produit` ASC) VISIBLE,
  INDEX `fk_commande_has_produit_commande1_idx` (`commande_numero` ASC) VISIBLE,
  CONSTRAINT `fk_commande_has_produit_commande1`
    FOREIGN KEY (`commande_numero`)
    REFERENCES `ventesdb`.`commande` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_has_produit_produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `ventesdb`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventesdb`.`suivi_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventesdb`.`suivi_commande` (
  `commande_numero` INT NOT NULL,
  `statut` VARCHAR(45) NULL,
  `date_envoi` DATE NULL,
  `date_reception` DATE NULL,
  PRIMARY KEY (`commande_numero`),
  CONSTRAINT `fk_suivi_commande_commande1`
    FOREIGN KEY (`commande_numero`)
    REFERENCES `ventesdb`.`commande` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
