-- MySQL Script generated by MySQL Workbench
-- Wed Aug 21 14:59:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema xyBankDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema xyBankDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xyBankDb` DEFAULT CHARACTER SET utf8 ;
USE `xyBankDb` ;

-- -----------------------------------------------------
-- Table `xyBankDb`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyBankDb`.`compte` ;

CREATE TABLE IF NOT EXISTS `xyBankDb`.`compte` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(64) NULL,
  `solde` DOUBLE NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyBankDb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyBankDb`.`client` ;

CREATE TABLE IF NOT EXISTS `xyBankDb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(64) NOT NULL,
  `nom` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyBankDb`.`operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyBankDb`.`operation` ;

CREATE TABLE IF NOT EXISTS `xyBankDb`.`operation` (
  `id` INT NOT NULL,
  `montant` DOUBLE NOT NULL,
  `label` VARCHAR(64) NOT NULL,
  `date` DATETIME NOT NULL,
  `num_compte` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operation_compte1_idx` (`num_compte` ASC) VISIBLE,
  CONSTRAINT `fk_operation_compte`
    FOREIGN KEY (`id`)
    REFERENCES `xyBankDb`.`compte` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operation_compte1`
    FOREIGN KEY (`num_compte`)
    REFERENCES `xyBankDb`.`compte` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyBankDb`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyBankDb`.`adresse` ;

CREATE TABLE IF NOT EXISTS `xyBankDb`.`adresse` (
  `client_id` INT NOT NULL,
  `rue` INT NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`client_id`),
  CONSTRAINT `fk_adresse_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `xyBankDb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xyBankDb`.`client_compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xyBankDb`.`client_compte` ;

CREATE TABLE IF NOT EXISTS `xyBankDb`.`client_compte` (
  `client_id` INT NOT NULL,
  `compte_numero` INT NOT NULL,
  PRIMARY KEY (`client_id`, `compte_numero`),
  INDEX `fk_client_has_compte_compte1_idx` (`compte_numero` ASC) VISIBLE,
  INDEX `fk_client_has_compte_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_compte_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `xyBankDb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_compte_compte1`
    FOREIGN KEY (`compte_numero`)
    REFERENCES `xyBankDb`.`compte` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
